### PR TITLE
Feature - Substring Search

### PR DESCRIPTION
**Pull request by mishuan**
-now allows search with substring
    -ie, ich will return michael, mich, ficher, ...
-calls wildcard query in elasticsearch

### CODE REVIEW

**Comment by untoldone** [comment]
@mishuan Could you please describe your use case a bit? I'd like to be sure this would be useful to everyone with a category of problem to solve rather than too specific a problem.

In addition, could you make sure '?' and '*' between your two "*"s are somehow escaped?

Thanks for taking the time to submit this!

**Comment by mishuan** [comment]
@untoldone Thanks for the feedback!

Rather than just having prefix search, substring search allows one to find names containing a certain pattern.  This feature is the same as ctrl+f when searching through a text.  For example searching "mit" will return "mitchell", "smith", "schmit", "dimitri", "emit", etc.  It is just a much broader query compared to just prefix searching. 

Regarding the second point, I do not quite see the issue.  Please clarify!

Thanks!

**Comment by untoldone** [comment]
Michael, thanks for the details -- though I'm still not sure I understand
your scenario.

I do follow the goal of the code is to search for a substring -- but I'm
curious what the specific use case is in the context of the API. What is
the sources of the substrings in your application? I've had a few asks for
features around autocomplete which is where fuzzy + prefix came from -- the
idea is you can fuzzy search for individual words and prefix match the last
string to do autocomplete.

The second point was more that what your implementation does isn't exactly
a substring search. Perhaps a better example: searching for an NPI with the
practice_address.city substring of 'n franc' will return zero results since
elastic search will search through tokens rather than phrases (it will
search "san" and "francisco" and not find a match to either). In addition,
someone could throw a '*' or a '?' into a substring search and get a
wild-card like result. If it does make sense to add wildcards -- i'd think
it would make more sense to just add wildcard without the two '*'s added
for the user. This said, I'd still be interested in learning about the use
cases before adding something like this.

**Comment by untoldone** [comment]
Reply by email appeared to hide most of my last response... here it is repeated ...

"
Michael, thanks for the details -- though I'm still not sure I understand
your scenario.

I do follow the goal of the code is to search for a substring -- but I'm
curious what the specific use case is in the context of the API. What is
the sources of the substrings in your application? I've had a few asks for
features around autocomplete which is where fuzzy + prefix came from -- the
idea is you can fuzzy search for individual words and prefix match the last
string to do autocomplete.

The second point was more that what your implementation does isn't exactly
a substring search. Perhaps a better example: searching for an NPI with the
practice_address.city substring of 'n franc' will return zero results since
elastic search will search through tokens rather than phrases (it will
search "san" and "francisco" and not find a match to either). In addition,
someone could throw a '*' or a '?' into a substring search and get a
wild-card like result. If it does make sense to add wildcards -- i'd think
it would make more sense to just add wildcard without the two '*'s added
for the user. This said, I'd still be interested in learning about the use
cases before adding something like this.
"

@mishuan Any further thoughts here?

**Comment by untoldone** [comment]
Closing this without further input. Feel free to reopen if you can give more info.

**Pull request closed without merging**
